blank_issues_enabled: true
contact_links:
  - name: ðŸ“š Documentation
    url: https://github.com/ArtemStepanov/caddy-admin-ui/tree/main/docs
    about: Check the documentation for help and guides
  - name: ðŸ’¬ Discussions
    url: https://github.com/ArtemStepanov/caddy-admin-ui/discussions
    about: Ask questions and discuss ideas with the community
